Models/CartItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class CartItem
    {
        [Key]
        public string ItemId { get; set; }

        [Required]
        public string CartId { get; set; }

        [Required]
        public int Quantity { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public System.DateTime DateCreated { get; set; }

        [Required]
        public int ProductId { get; set; }

        [Required]
        public virtual Product Product { get; set; }
    }
}

Models/Discount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class Discount
    {
        [Key]
        public int DisID { get; set; }

        [Required]
        public string ToyName { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [Required]
        public DateTime EndDate { get; set; }

        [Required]
        public decimal totalDiscount { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ToysShop_Core_Project.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LoginModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class LoginModel
    {

        [Key]
        public int ID { get; set; }
        public string Username { get; set; }
        public int Password { get; set; }
    }
}

Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class Product
    {
        [Key]
        public string ItemId { get; set; }

        [Required]
        public string CartId { get; set; }

        [Required]
        public int Quantity { get; set; }

        [Required]
        public int ProductID { get; set; }

        [Required]
        public string Brandname { get; set; }

    }
}

Models/Toy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class Toy
    {
        [Key]
        public string ItemId { get; set; }

        [Required]
        public string ToyName { get; set; }

        [Required]
        public int Quantity { get; set; }

        [Required]
        public string ToyColor { get; set; }

        [Required]
        public decimal Price { get; set; }

        public string Dalia { get; set; }
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class User
    {
         
        [Key]
        public int UserID { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string MiddleName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string FullName { get; set; }

        [Required]
        public int Number { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Address { get; set; }
    }
}

Models/ffff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ToysShop_Core_Project.Models
{
    public class ffff
    {
    }
}

Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ToysShop_Core_Project.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ToysShop_Core_Project.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }
    }
}

Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ToysShop_Core_Project.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult DDDD()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ToysShop_Core_Project.Models;

namespace ToysShop_Core_Project.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }

        
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToysShop_Core_Project.Models;

namespace ToysShop_Core_Project.Controllers
{
    public class LoginController : Controller
    {     
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }


            return View();
            
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ToysShop_Core_Project.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Services()
        {
            return View();
        }
    }
}

Controllers/ShopNowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ToysShop_Core_Project.Controllers
{
    public class ShopNowController : Controller
    {
        public IActionResult ShopNow()
        {
            return View();
        }
    }
}

Views/Contact/Contact.cshtml

@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="inner_page-banner one-img">
</div>
<!--//banner -->
<!-- short -->
<div class="using-border py-3">
    <div class="inner_breadcrumb  ml-4">
        <ul class="short_ls">
            <li>
                <a href="index.html">Home</a>
                <span>/ /</span>
            </li>
            <li>Contact</li>
        </ul>
    </div>
</div>
<!-- //short-->
<!--contact -->
<section class="contact py-lg-4 py-md-3 py-sm-3 py-3">
    <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
        <h3 class="title text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3">Contact US</h3>
        <div class="contact-list-grid">
            <form action="#" method="post">
                <div class=" agile-wls-contact-mid">
                    <div class="form-group contact-forms">
                        <input type="text" class="form-control" placeholder="Name">
                    </div>
                    <div class="form-group contact-forms">
                        <input type="email" class="form-control" placeholder="Enter">
                    </div>
                    <div class="form-group contact-forms">
                        <input type="text" class="form-control" placeholder="Phone">
                    </div>
                    <div class="form-group contact-forms">
                        <textarea class="form-control" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-block sent-butnn">Send</button>
                </div>
            </form>
        </div>
    </div>
    <!--//contact-map -->
</section>
<!--subscribe-address-->
<section class="subscribe">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 map-info-right px-0">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3150859.767904157!2d-96.62081048651531!3d39.536794757966845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1408111832978"> </iframe>
            </div>
            <div class="col-lg-6 col-md-6 address-w3l-right text-center">
                <div class="address-gried ">
                    <span class="far fa-map"></span>
                    <p>25478 Road St.121<br>USA New Hill
                    <p>
                </div>
                <div class="address-gried mt-3">
                    <span class="fas fa-phone-volume"></span>
                    <p> +(000)123 4565<br>+(010)123 4565</p>
                </div>
                <div class=" address-gried mt-3">
                    <span class="far fa-envelope"></span>
                    <p>
                        <a href="mailto:info@example.com">info@example1.com</a>
                        <br><a href="mailto:info@example.com">info@example2.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--//subscribe-address-->
<section class="sub-below-address py-lg-4 py-md-3 py-sm-3 py-3">
    <div class="container py-lg-5 py-md-5 py-sm-4 py-3">
        <h3 class="title clr text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3">Get In Touch Us</h3>
        <div class="icons mt-4 text-center">
            <ul>
                <li><a href="#"><span class="fab fa-facebook-f"></span></a></li>
                <li><a href="#"><span class="fas fa-envelope"></span></a></li>
                <li><a href="#"><span class="fas fa-rss"></span></a></li>
                <li><a href="#"><span class="fab fa-vk"></span></a></li>
            </ul>
            <p class="my-3">
                velit sagittis vehicula. Duis posuere
                ex in mollis iaculis. Suspendisse tincidunt
                velit sagittis vehicula. Duis posuere
                velit sagittis vehicula. Duis posuere
            </p>
        </div>
        <div class="email-sub-agile">
            <form action="#" method="post">
                <div class="form-group sub-info-mail">
                    <input type="email" class="form-control email-sub-agile" placeholder="Email">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn subscrib-btnn">Subscribe</button>
                </div>
            </form>
        </div>
    </div>
</section>


Views/Default/DDDD.cshtml

@{
    ViewData["Title"] = "DDDD";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DDDD</h2>


Views/Login/Login.cshtml
@using ToysShop_Core_Project.Models
@model LoginModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="using-border py-3">
    <div class="inner_breadcrumb  ml-4">
        <ul class="short_ls">
            <li>
                <a href="index.html">Home</a>
                <span>/ /</span>
            </li>
            <li>Login</li>
        </ul>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="clearfix"></div>
<div class="container">
    <div class="col-md-8">
        <section id="loginForm">
            <h4 class="container">Use a local account to log in.</h4>
            <hr />
            <div class="form-group">
                <label class="col-md-2 control-label">E-mail</label>
                <div class="col-md-10">
                    <input type="text" name="fEmail" class="form-control" />

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label">Password</label>
                <div class="col-md-10">
                    <input type="text" name="fName" class="form-control" />

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Log in" class="btn btn-default" />
                </div>
            </div>


        </section>
    </div>

</div>


Views/Services/Services.cshtml

@{
    ViewData["Title"] = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="inner_page-banner one-img">
</div>
<!--//banner -->
<!-- short -->
<div class="using-border py-3">
    <div class="inner_breadcrumb  ml-4">
        <ul class="short_ls">
            <li>
                <a href="index.html">Home</a>
                <span>/ /</span>
            </li>
            <li>Service</li>
        </ul>
    </div>
</div>
<!-- //short-->
<!--service -->
<section class="service py-lg-4 py-md-3 py-sm-3 py-3">
    <div class="container py-lg-5 py-md-4 py-sm-4 py-3">
        <h3 class="title text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3">Services</h3>
        <div class="row text-center">
            <div class="col-lg-4 col-md-6 abut-gride">
                <span class="fas fa-truck"></span>
                <h5>Shipping</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
            <div class="col-lg-4 col-md-6 abut-gride">
                <span class="fas fa-phone-volume"></span>
                <h5>Support</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
            <div class="col-lg-4 col-md-6 abut-gride">
                <span class="fas fa-undo"></span>
                <h5> Return</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
            <div class="col-lg-4 col-md-6 mt-lg-4 mt-3 abut-gride">
                <span class="fas fa-money-bill-alt"></span>
                <h5>Online Cash</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
            <div class="col-lg-4 col-md-6 mt-lg-4 mt-3 abut-gride">
                <span class="fas fa-exchange-alt"></span>
                <h5>Exchange</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
            <div class="col-lg-4 col-md-6 mt-lg-4 mt-3 abut-gride">
                <span class="fas fa-thumbs-up"></span>
                <h5>Quality</h5>
                <p class="mt-3">
                    velit sagittis vehicula. Duis posuere
                    ex in mollis iaculis. Suspendisse tincidunt
                </p>
            </div>
        </div>
    </div>
</section>
<!--//service -->
<!--subscribe-address-->
<section class="subscribe">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-6 map-info-right px-0">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3150859.767904157!2d-96.62081048651531!3d39.536794757966845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1408111832978"> </iframe>
            </div>
            <div class="col-lg-6 col-md-6 address-w3l-right text-center">
                <div class="address-gried ">
                    <span class="far fa-map"></span>
                    <p>25478 Road St.121<br>USA New Hill
                    <p>
                </div>
                <div class="address-gried mt-3">
                    <span class="fas fa-phone-volume"></span>
                    <p> +(000)123 4565<br>+(010)123 4565</p>
                </div>
                <div class=" address-gried mt-3">
                    <span class="far fa-envelope"></span>
                    <p>
                        <a href="mailto:info@example.com">info@example1.com</a>
                        <br><a href="mailto:info@example.com">info@example2.com</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--//subscribe-address-->
<section class="sub-below-address py-lg-4 py-md-3 py-sm-3 py-3">
    <div class="container py-lg-5 py-md-5 py-sm-4 py-3">
        <h3 class="title clr text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3">Get In Touch Us</h3>
        <div class="icons mt-4 text-center">
            <ul>
                <li><a href="#"><span class="fab fa-facebook-f"></span></a></li>
                <li><a href="#"><span class="fas fa-envelope"></span></a></li>
                <li><a href="#"><span class="fas fa-rss"></span></a></li>
                <li><a href="#"><span class="fab fa-vk"></span></a></li>
            </ul>
            <p class="my-3">
                velit sagittis vehicula. Duis posuere
                ex in mollis iaculis. Suspendisse tincidunt
                velit sagittis vehicula. Duis posuere
                velit sagittis vehicula. Duis posuere
            </p>
        </div>
        <div class="email-sub-agile">
            <form action="#" method="post">
                <div class="form-group sub-info-mail">
                    <input type="email" class="form-control email-sub-agile" placeholder="Email">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn subscrib-btnn">Subscribe</button>
                </div>
            </form>
        </div>
    </div>
</section>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToysShop_Core_Project</title>

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href="~/css/fontawesome-all.min.css" rel="stylesheet" type="text/css" media="all">
    <!-- //font-awesome icons -->
    <!-- For Clients slider -->
    <link rel="stylesheet" href="~/css/flexslider.css" type="text/css" media="all" />
    <!--flexs slider-->
    <link href="~/css/JiSlider.css" rel="stylesheet">
    <!--Shoping cart-->
    <link rel="stylesheet" href="~/css/shop.css" type="text/css" />
    <!--//Shoping cart-->
    <!--stylesheets-->
    <link href="~/css/style.css" rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href="//fonts.googleapis.com/css?family=Sunflower:500,700" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
</head>
<body>
    <div class="header-outs" id="home">
        <div class="header-bar">
            <div class="info-top-grid">
                <div class="info-contact-agile">
                    <ul>
                        <li>
                            <span class="fas fa-phone-volume"></span>
                            <p>+(000)123 4565 32</p>
                        </li>
                        <li>
                            <span class="fas fa-envelope"></span>
                            <p><a href="mailto:info@example.com">info@example1.com</a></p>
                        </li>
                        <li>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="container-fluid">
                <div class="hedder-up row">
                    <div class="col-lg-3 col-md-3 logo-head">
                        <h1><a class="navbar-brand" href="index.html">Toys-Shop</a></h1>
                    </div>
                    <div class="col-lg-5 col-md-6 search-right">
                        <form class="form-inline my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search">
                            <button class="btn" type="submit">Search</button>
                        </form>
                    </div>
                    <div class="col-lg-4 col-md-3 right-side-cart">
                        <div class="cart-icons">
                            <ul>
                                <li>
                                    <span class="far fa-heart"></span>
                                </li>
                                <li>
                                    <button type="button" data-toggle="modal" data-target="#exampleModal"> <span class="far fa-user"></span></button>
                                </li>
                                <li class="toyscart toyscart2 cart cart box_1">
                                    <form action="#" method="post" class="last">
                                        <input type="hidden" name="cmd" value="_cart">
                                        <input type="hidden" name="display" value="1">
                                        <button class="top_toys_cart" type="submit" name="submit" value="">
                                            <span class="fas fa-cart-arrow-down"></span>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="navbar navbar-expand-lg navbar-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
                    <ul class="navbar-nav ">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="About" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Services" asp-action="Services">Service</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="ShopNow" asp-action="ShopNow">Shop Now</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Contact">Contact</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- Slideshow 4 -->
        
    </div>

    <partial name="_CookieConsentPartial" />

    <div>
        @RenderBody()
        <hr />
        <footer class="py-lg-4 py-md-3 py-sm-3 py-3 text-center">
            <div class="copy-agile-right">
                <p>
                    © 2018 Toys-Shop. All Rights Reserved | Design by <a href="http://www.W3Layouts.com" target="_blank">W3Layouts</a>
                </p>
            </div>
        </footer>
        <!-- //footer -->
        <!-- Modal 1-->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="register-form">
                            <form action="#" method="post">
                                <div class="fields-grid">
                                    <div class="styled-input">
                                        <input type="text" placeholder="Your Name" name="Your Name" required="">
                                    </div>
                                    <div class="styled-input">
                                        <input type="email" placeholder="Your Email" name="Your Email" required="">
                                    </div>
                                    <div class="styled-input">
                                        <input type="password" placeholder="password" name="password" required="">
                                    </div>
                                    <button type="submit" class="btn subscrib-btnn">Login</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- //Modal 1-->
        <!--js working-->
        <script src='~/js/jquery-2.2.3.min.js'></script>
        <!--//js working-->
        <!-- cart-js -->
        <script src="~/js/minicart.js"></script>
        <script>
            toys.render();

            toys.cart.on('toys_checkout', function (evt) {
                var items, len, i;

                if (this.subtotal() > 0) {
                    items = this.items();

                    for (i = 0, len = items.length; i < len; i++) { }
                }
            });
        </script>
        <!-- //cart-js -->
        <!--responsiveslides banner-->
        <script src="~/js/responsiveslides.min.js"></script>
        <script>
            // You can also use "$(window).load(function() {"
            $(function () {
                // Slideshow 4
                $("#slider4").responsiveSlides({
                    auto: true,
                    pager: false,
                    nav: true,
                    speed: 900,
                    namespace: "callbacks",
                    before: function () {
                        $('.events').append("<li>before event fired.</li>");
                    },
                    after: function () {
                        $('.events').append("<li>after event fired.</li>");
                    }
                });

            });
        </script>
        <!--// responsiveslides banner-->
        <!--slider flexisel -->
        <script src="~/js/jquery.flexisel.js"></script>
        <script>
            $(window).load(function () {
                $("#flexiselDemo1").flexisel({
                    visibleItems: 3,
                    animationSpeed: 3000,
                    autoPlay: true,
                    autoPlaySpeed: 2000,
                    pauseOnHover: true,
                    enableResponsiveBreakpoints: true,
                    responsiveBreakpoints: {
                        portrait: {
                            changePoint: 480,
                            visibleItems: 1
                        },
                        landscape: {
                            changePoint: 640,
                            visibleItems: 2
                        },
                        tablet: {
                            changePoint: 768,
                            visibleItems: 2
                        }
                    }
                });

            });
        </script>
        <!-- //slider flexisel -->
        <!-- start-smoth-scrolling -->
        <script src="~/js/move-top.js"></script>
        <script src="~/js/easing.js"></script>
        <script>
            jQuery(document).ready(function ($) {
                $(".scroll").click(function (event) {
                    event.preventDefault();
                    $('html,body').animate({
                        scrollTop: $(this.hash).offset().top
                    }, 900);
                });
            });
        </script>
        <!-- start-smoth-scrolling -->
        <!-- here stars scrolling icon -->
        <script>
            $(document).ready(function () {

                var defaults = {
                    containerID: 'toTop', // fading element id
                    containerHoverID: 'toTopHover', // fading element hover id
                    scrollSpeed: 1200,
                    easingType: 'linear'
                };
                $().UItoTop({
                    easingType: 'easeOutQuart'
                });

            });
        </script>
        <!-- //here ends scrolling icon -->
        <!--bootstrap working-->
        <script src="~/js/bootstrap.min.js"></script>

    </div>

    
</body>
</html>